import { Inter, Bebas_Neue, Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Provider from "@/components/provider";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const bebas = Bebas_Neue({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  variable: "--font-bebas",
});
const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "400", "700"],
  variable: "--font-nunito",
});

export const metadata = {
  title: "Manchester United Unofficial Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  ${bebas.variable} ${nunito.variable}`}
      >
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
        <div id="modal"></div>
      </body>
    </html>
  );
}
